#
#        » Leaked by @FichaDev «
#        Studio: t.me/FichaDev
#        Hentai: t.me/FichaHentai
#
name: FichaCommandWhitelist
version: '1.0'
main: ua.fichamine.fichacommandwhitelist.FichaCommandWhitelist
api-version: 1.13
depend: [CommandWhitelist, ProtocolLib]
website: https://t.me/FichaDev
authors:
  - Smail
  - FichaDev